export const orderTypes = {
  printType: [
    "بطاقات عمل",
    "بروشورات",
    "بوسترات",
    "فواتير / إيصالات",
    "مطويات",
    "أظرف",
    "دفاتر",
    "ستيكرات",
    "كروت دعوة",
    "بانرات",
  ],
  paperType: [
    "Couché لامع",
    "Couché مطفي",
    "Bond عادي",
    "Ivory",
    "Kraft",
    "Sticker لاصق",
  ],
  colorOption: ["أبيض وأسود", "ملون كامل (CMYK)", "لون خاص (Pantone)"],
  sideOption: ["وجه واحد", "وجهين"],
  size: ["A4", "A5", "A6", "Letter", "Legal"],
  finishingOptions: [
    "تغليف لامع",
    "تغليف مطفي",
    "تجليد حلزوني",
    "تدبيس",
    "قص خاص بالشكل",
    "شعار مذهب / فضي",
    "رفع بالشعار (Emboss / Deboss)",
  ],
  status: [
    "جديدة",
    "قيد المراجعة",
    "قيد الطباعة",
    "جاهزة للتسليم",
    "مرفوضة",
    "ملغي",
  ],
  departmentWork: ["CTP", "Digital", "Offset", "Cutting_Binding"],
};
